### ISSUE TITLE
The dimension of the point descritptors

### ISSUE THREAD

**Issue by haoyu94** [paul007pl/GMCNet#1]
Hi, thanks for your great work! 

I am curious about the dimension of your finally generated point descriptors. It seems it is not mentioned in your arxiv paper.

**Comment by paul007pl** [comment]
Hi~ Thank you for asking. The final dimension is set to 128 for all reported experiments.  
For different settings, the feature size of each component is slightly different.  Generally, noisy cases require middle-level and high-level feature descriptors with larger feature dimensions, while relatively smaller sizes are fine with clean cases.

**Comment by haoyu94** [comment]
Thanks for your quick response. I'll close the issue.
