### ISSUE TITLE
Error while training (NameError: name 'furthest_point_sample' is not defined)

### ISSUE THREAD

**Issue by gowda-95** [paul007pl/GMCNet#8]
![image](https://user-images.githubusercontent.com/103493119/169966664-1e739cb7-f770-4fb3-9074-91a233c1748d.png)

Hi, Thank you for the nice work. 

Though I did install mm3d_pn2 as mentioned in the installation section, I am facing the error, "NameError: name 'furthest_point_sample' is not defined
Segmentation fault (core dumped)" , I have attached the reference pic above. 

I have also attached a screenshot to show the installation confirmation for source setup.sh below. 
![WhatsApp Image 2022-05-24 at 8 13 51 AM](https://user-images.githubusercontent.com/103493119/169967306-3fe1915a-1fec-4b8d-bc92-c9df89177404.jpeg)

Kindly let me know where I might be erring. Many thanks in advance.

**Comment by paul007pl** [comment]
Thanks for asking!
Actually, you should first install and compile all the required functions before you could successfully run this project.
Please follow my install instructions first, and then you could try again.
Once you successfully install all the required libraries, you will not see those errors.
